//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicTick.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumVideo
    {
        public long Id { get; set; }
        public Nullable<long> AlbumId { get; set; }
        public string Title { get; set; }
        public string Video { get; set; }
    }
}
