//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicTick.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long Id { get; set; }
        public Nullable<long> AppointmentSlotId { get; set; }
        public Nullable<long> StudioId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string Description { get; set; }
    }
}
