//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicTick.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long Id { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<long> StudioId { get; set; }
        public string FCMToken { get; set; }
        public string Type { get; set; }
        public string InviteStatus { get; set; }
        public Nullable<long> PhotographerId { get; set; }
        public string Image { get; set; }
    }
}
