//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicTick.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string GalleryPin { get; set; }
        public string SelectionPin { get; set; }
        public Nullable<bool> AllowDownload { get; set; }
        public string GalleryCover { get; set; }
        public string WatterMark { get; set; }
        public long StudioId { get; set; }
        public Nullable<bool> IsSelectionDone { get; set; }
    }
}
