//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicTick.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studio
    {
        public long Id { get; set; }
        public Nullable<long> StateId { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string StudioLogo { get; set; }
        public string About { get; set; }
        public string Services { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string StudioOwner { get; set; }
        public string Country { get; set; }
        public Nullable<long> CityId { get; set; }
        public string PinCode { get; set; }
        public string InviteMessage { get; set; }
        public string WaterMark { get; set; }
        public string Position { get; set; }
        public string Font { get; set; }
        public string FontStyle { get; set; }
        public string Opacity { get; set; }
        public string FontSize { get; set; }
        public string WaterMarkImage { get; set; }
        public string WaterMarkType { get; set; }
    }
}
